version: '3.7'

services:

    postgres:
        build:
            context: .
            dockerfile: pg-Dockerfile
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=dspace
            - POSTGRES_USER=dspace
        env_file:
            - proj.env
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        command: ["postgres", "-c", "log_statement=all"]

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - 5555:80
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped

volumes:
    postgres_data: